"""
Django settings for eletromaciel_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# 🌟 FORÇAR O DJANGO A DESATIVAR O RECURSO 'RETURNING' COMPATIBILIZANDO COM MARIADB ANTIGO
from django.db import connections
from django.db.backends.mysql.base import DatabaseFeatures

# Força o sinalizador de recursos a dizer "Não suportado" para inserções com retorno
DatabaseFeatures.can_return_rows_from_insert = False
DatabaseFeatures.can_return_ids_from_insert = False

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',  # Adicione o corsheaders aqui
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken', # Adicione o authtoken para autenticação baseada em token
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Adicione o CorsMiddleware aqui
]

ROOT_URLCONF = 'eletromaciel_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eletromaciel_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # Use o backend personalizado para MySQL/MariaDB
        'NAME': 'db_eletromaciel',
        'USER': 'root',
        'PASSWORD':'',  # Insira a senha se houver ,
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            
        },
        # ⏬ ADICIONE ESTA PARTE EXATAMENTE AQUI:
        'ASSUME_REAL_SERVER_VERSION': '10.3.0',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Permite que o WordPress local (e o navegador) faça requisições para a API
CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
    "http://localhost:8080",  # <-- Adicionando a porta 8080 do XAMPP
    "http://127.0.0.1:8080",  # <-- Adicionando o IP com a porta 8080
]

# Se o seu WordPress usa alguma porta específica (ex: http://localhost:8080), adicione ela também:
# CORS_ALLOWED_ORIGINS += ["http://localhost:8080"]
CORS_ALLOW_ALL_ORIGINS = True
# Adicione isso no final do seu settings.py junto com as outras configs de CORS
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",  # <-- ESSA LINHA PERMITE O ENVIO DO TOKEN!
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]